// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_ADMIN_JWT = process.env.SUPABASE_ADMIN_JWT;

  console.log('[supabase-admin] URL:', SUPABASE_URL ?? '(ausente)');
  console.log('[supabase-admin] SUPABASE_ADMIN_JWT existe:', !!SUPABASE_ADMIN_JWT);
  console.log('[supabase-admin] prefixo da chave:', SUPABASE_ADMIN_JWT ? SUPABASE_ADMIN_JWT.slice(0, 20) : '(ausente)');
  console.log('[supabase-admin] formato:', SUPABASE_ADMIN_JWT?.startsWith('eyJ') ? 'JWT ✓' : SUPABASE_ADMIN_JWT?.startsWith('sb_') ? 'sb_* ✗' : '(ausente ou desconhecido)');

  if (!SUPABASE_URL || !SUPABASE_ADMIN_JWT) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_ADMIN_JWT ? ['SUPABASE_ADMIN_JWT'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Cadastre SUPABASE_ADMIN_JWT no painel do Lovable.`;
    console.error(`[supabase-admin] ERRO: ${message}`);
    throw new Error(message);
  }

  console.log('[supabase-admin] cliente inicializado com sucesso');
  return createClient<Database>(SUPABASE_URL, SUPABASE_ADMIN_JWT, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
